name: CI

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Configure
        run: cmake --preset gcc-default
      
      - name: Build
        run: cmake --build --preset build-tests-gcc
      
      - name: Run tests
        run: ctest --preset test-gcc
      
      # TODO: coverage

  python_test:
    name: Python Test
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout (line-protocol)
        uses: actions/checkout@v4
        with:
          repository: c4deszes/bike-line-protocol
          path: line-protocol

      - name: Setup line-protocol
        working-directory: line-protocol/python-lib
        run: python -m pip install -e .[dev]

      - name: Setup Python library
        working-directory: python-lib
        run: python -m pip install -e .[dev]
      
      - name: Run tests
        working-directory: python-lib
        run: python -m pytest --cov=line_flash --cov-report=xml

      # TODO: results and coverage?
      
# TODO: bundle pyinstaller

# TODO: linting?

  sphinx_docs:
    name: Documentation
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: python -m pip install -r docs/requirements.txt

      - name: Build documentation
        run: python -m sphinx -b html -E docs docs/_build

      # TODO: archive
